services:
  # PHP-FPM for Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_hs_web_dev
    volumes:
      - .:/var/www/html
      - ./storage/logs:/var/log/php
    depends_on:
      - postgres
    networks:
      - laravel_network_hs_web_dev

  # Nginx for Laravel
  nginx_backend:
    image: nginx:alpine
    container_name: server_hs_web_dev
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network_hs_web_dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: pg_database_hs_web_dev
    environment:
      POSTGRES_USER: dev_
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dev_db
    ports:
      - "5433:5432" # already have db instance running for my other project in port 5432
    volumes:
      - postgres_data_hs_web_dev:/var/lib/postgresql/data
    networks:
      - laravel_network_hs_web_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_hs_web_dev:

networks:
  laravel_network_hs_web_dev:
    name: laravel_network_hs_web_dev
