[build]
builder = "nixpacks"
buildCommand = "./build-railway.sh"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["nodejs", "npm", "php"] 